FROM jupyter/minimal-notebook

WORKDIR /app

COPY src /app/src
COPY tools /app/tools

COPY pyproject.toml ./
COPY README.md ./
COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt
